server:
  port: 8082

spring:
  application:
    name: admin-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db   # The JDBC URL for the database
    username: postgres                                    # The username for the database
    password: password                                  # The password for the database
    driver-class-name: org.postgresql.Driver       # The JDBC driver class
    
    
  jpa:
    hibernate:
      ddl-auto: update      # Automatically update the database schema
    show-sql: true          # Log SQL statements
    properties:
      hibernate:
        format_sql: true    # Format the logged SQL statements
        
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
    # Kafka bootstrap - change to your env

  kafka:
    bootstrap-servers: localhost:9092
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
logging:
  level:
    root: DEBUG

  file:
    name: /log/AdminService.log
    max-size: 10MB
    max-history: 5