spring:
  application:
    name: AdminService
    
  datasource:
    url: jdbc:postgresql://localhost:5432/admin_db   # The JDBC URL for the database
    username: postgres                                    # The username for the database
    password: password                                  # The password for the database
    driver-class-name: org.postgresql.Driver       # The JDBC driver class
    
    
  jpa:
    hibernate:
      ddl-auto: update      # Automatically update the database schema
    show-sql: true          # Log SQL statements
    properties:
      hibernate:
        format_sql: true    # Format the logged SQL statements
        
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/